apiVersion: v1
kind: Service
metadata:
  name: flomesh-console
  labels:
    {{- include "flomesh-console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{ if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort | default 30000 }}
{{ end }}
  selector:
    {{- include "flomesh-console.selectorLabels" . | nindent 4 }}
